_base_: '../_base_/cityscapes.yml'

model:
  type: PPLiteSeg
  backbone:
    type: STDC1
    pretrained: Null
  arm_out_chs: [32, 64, 128]
  seg_head_inter_chs: [32, 64, 64]

optimizer:
  type: SGD
  weight_decay: 0.0005

loss:
  types:
    - type: OhemCrossEntropyLoss
      min_kept: 130000   # batch_size * 1024 * 512 // 16
    - type: OhemCrossEntropyLoss
      min_kept: 130000
    - type: OhemCrossEntropyLoss
      min_kept: 130000
  coef: [1, 1, 1]

batch_size: 4
iters: 160000

lr_scheduler:
  learning_rate: 0.005
