_base_: '../_base_/pascal_voc12aug.yml'

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1, 0.4]

model:
  type: PSPNet
  backbone:
    type: ResNet50_vd
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
  enable_auxiliary_loss: True
  align_corners: False
  pretrained: null
