_base_: '../../_base_/global_configs.yml'

batch_size: 1
iters: 30000

model:
  type: NNUNet
  plan_path: msd_lung/preprocessed/Task006_Lung/nnUNetPlansv2.1_plans_2D.pkl
  stage: 0

train_dataset:
  type: MSDDataset
  plans_name: nnUNetPlansv2.1_plans_2D.pkl
  dataset_root: /
  result_dir: /
  raw_data_dir: msd_lung/Task06_Lung
  decathlon_dir: msd_lung/Task006_Lung
  cropped_data_dir: msd_lung/cropped/Task006_Lung
  preprocessed_dir: msd_lung/preprocessed/Task006_Lung
  plan2d: True
  plan3d: False
  num_batches_per_epoch: 250
  fold: 1
  stage: 0
  unpack_data: True
  cascade: False
  mode: train

val_dataset:
  type: MSDDataset
  plans_name: nnUNetPlansv2.1_plans_2D.pkl
  dataset_root: /
  result_dir: /
  raw_data_dir: msd_lung/Task06_Lung
  decathlon_dir: msd_lung/Task006_Lung
  cropped_data_dir: msd_lung/cropped/Task006_Lung
  preprocessed_dir: msd_lung/preprocessed/Task006_Lung
  num_batches_per_epoch: 50
  fold: 1
  stage: 0
  unpack_data: True
  cascade: False
  mode: val


optimizer:
  type: sgd
  momentum: 0.99
  weight_decay: 0.00003
  use_nesterov: True


lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: MultipleLoss
      plan_path: msd_lung/preprocessed/Task006_Lung/nnUNetPlansv2.1_plans_2D.pkl
      stage: 0
      losses:
        - type: DC_and_CE_loss
          do_bg: False
          batch_dice: True
      coef: [1.0]
  coef: [1]
