Global:
  model_dir: ./ppmobileseg_base_export
  model_filename: model.pdmodel
  params_filename: model.pdiparams

Distillation:
  alpha: 1.0
  loss: l2
  node:
  - conv2d_211.tmp_0 # change to the name of the output of the last conv in the model.pdmodel in netron

QuantAware:
  onnx_format: False
  quantize_op_types:
  - conv2d
  - depthwise_conv2d

TrainConfig:
  epochs: 20
  eval_iter: 1000
  learning_rate: 0.0005
  optimizer_builder:
    optimizer: 
      type: SGD
    weight_decay: 4.0e-05  
