_base_: 'abdomen.yml'

model:
  type: TransUNet
  backbone:
    type: ResNet
    block_units: [3, 4, 9]
    width_factor: 1
  classifier: seg
  decoder_channels: [256, 128, 64, 16]
  hidden_size: 768
  n_skip: 3
  patches_grid: [14, 14]
  pretrained_path: https://paddleseg.bj.bcebos.com/paddleseg3d/synapse/abdomen/transunet_abdomen_224_224_1_14k_1e-2/pretrain_model.pdparams
  skip_channels: [512, 256, 64, 16]
  attention_dropout_rate: 0.0
  dropout_rate: 0.1
  mlp_dim: 3072
  num_heads: 12
  num_layers: 12
  num_classes: 9
  img_size: 224