# The ocrnet_hrnetw48 config for train benchmark
_base_: '../_base_/cityscapes.yml'

batch_size: 2
iters: 500

model:
  type: OCRNet
  backbone:
    type: HRNet_W48
    pretrained: Null
  num_classes: 19
  backbone_indices: [0]

optimizer:
  type: SGD

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
  coef: [1, 0.4]
