batch_size: 1
iters: 65078
# iters: 200

train_dataset:
  type: Cityscapes
  dataset_root: ../../dataset/cityscapes-for-nvidia
  mode: train
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0
    - type: RandomPaddingCrop
      crop_size: [2048, 1024]
#       crop_size: [769, 769]
    - type: RandomHorizontalFlip

#     - type: RandomDistort
#       brightness_range: 0.25
#       brightness_prob: 1
#       contrast_range: 0.25
#       contrast_prob: 1
#       saturation_range: 0.25
#       saturation_prob: 1
#       hue_range: 63
#       hue_prob: 1
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]


val_dataset:
  type: Cityscapes
  dataset_root: ../../dataset/cityscapes-for-nvidia
  mode: val
  transforms:
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

model:
#   type: MscaleOCRPretrain
  type: MscaleOCRFinetune
  params: None
#   pretrained: pretrain/ocr_pretrain/model.pdparams
  pretrained: pretrain/ocr_finetune_good/model.pdparams

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 0.0001

learning_rate:
  value: 0.002
#   value: 0.00002
  decay:
    type: poly
    power: 2
    end_lr: 0.0

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1, 0.4, 0.05, 0.05]
#   coef: [1, 0, 0.05, 0.05]
