_base_: '../_base_/cityscapes_autolabeling.yml'

batch_size: 1
iters: 160000

train_dataset:
  type: CityscapesAutolabeling
  dataset_root: ../../dataset/cityscapes-for-nvidia
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [2048, 1024]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

model:
  type: OCRNet
  backbone:
    type: HRNet_W64

    pretrained: 'pretrain/se_hrnet_w64.pdparams'
  num_classes: 19
  backbone_indices: [0]

optimizer:
  type: sgd

learning_rate:
  value: 0.01
  decay:
    type: poly
    power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
  coef: [1, 1]
