EVAL_CROP_SIZE: (2048, 1024) # (width, height), for unpadding rangescaling and stepscaling
TRAIN_CROP_SIZE: (1024, 1024) # (width, height), for unpadding rangescaling and stepscaling
AUG:
    AUG_METHOD: "stepscaling" # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: (640, 640) # (width, height), for unpadding
    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling
    MAX_SCALE_FACTOR: 2.0  # for stepscaling
    MIN_SCALE_FACTOR: 0.5  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    MIRROR: True
    FLIP: False
    FLIP_RATIO: 0.2
    RICH_CROP:
        ENABLE: True
        ASPECT_RATIO: 0.0
        BLUR: False
        BLUR_RATIO: 0.1
        MAX_ROTATION: 0
        MIN_AREA_RATIO: 0.0
        BRIGHTNESS_JITTER_RATIO: 0.4
        CONTRAST_JITTER_RATIO: 0.4
        SATURATION_JITTER_RATIO: 0.4
BATCH_SIZE: 12
MEAN: [0.5, 0.5, 0.5]
STD: [0.5, 0.5, 0.5]
DATASET:
    DATA_DIR: "./dataset/cityscapes/"
    IMAGE_TYPE: "rgb"  # choice rgb or rgba
    NUM_CLASSES: 19
    TEST_FILE_LIST: "dataset/cityscapes/val.list"
    TRAIN_FILE_LIST: "dataset/cityscapes/train.list"
    VAL_FILE_LIST: "dataset/cityscapes/val.list"
    VIS_FILE_LIST: "dataset/cityscapes/val.list"
    IGNORE_INDEX: 255
FREEZE:
    MODEL_FILENAME: "model"
    PARAMS_FILENAME: "params"
MODEL:
    DEFAULT_NORM_TYPE: "bn"
    MODEL_NAME: "fast_scnn"

TEST:
    TEST_MODEL: "snapshots/cityscape_fast_scnn/final/"
TRAIN:
    MODEL_SAVE_DIR: "snapshots/cityscape_fast_scnn/"
    SNAPSHOT_EPOCH: 10
SOLVER:
    LR: 0.001
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"
    NUM_EPOCHS: 100
