EVAL_CROP_SIZE: (2049, 1025) # (width, height), for unpadding rangescaling and stepscaling
TRAIN_CROP_SIZE: (769, 769) # (width, height), for unpadding rangescaling and stepscaling
AUG:
    AUG_METHOD: "stepscaling" # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: (2048, 1024) # (width, height), for unpadding
    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling
    MAX_SCALE_FACTOR: 2.0  # for stepscaling
    MIN_SCALE_FACTOR: 0.5  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    MIRROR: True
    TO_RGB: True
BATCH_SIZE: 16
DATASET:
    DATA_DIR: "./dataset/cityscapes/"
    IMAGE_TYPE: "rgb"  # choice rgb or rgba
    NUM_CLASSES: 19
    TEST_FILE_LIST: "dataset/cityscapes/val.list"
    TRAIN_FILE_LIST: "dataset/cityscapes/train.list"
    VAL_FILE_LIST: "dataset/cityscapes/val.list"
    VIS_FILE_LIST: "dataset/cityscapes/val.list"
    IGNORE_INDEX: 255
    SEPARATOR: " "
FREEZE:
    MODEL_FILENAME: "model"
    PARAMS_FILENAME: "params"
MODEL:
    DEFAULT_NORM_TYPE: "bn"
    MODEL_NAME: "deeplabv3p"
    DEEPLAB:
        ASPP_WITH_SEP_CONV: True
        DECODER_USE_SEP_CONV: True
        BACKBONE: "resnet_vd_50"
        BACKBONE_LR_MULT_LIST: [0.1, 0.1, 0.2, 0.2, 1.0]
TRAIN:
    PRETRAINED_MODEL_DIR: u"pretrained_model/resnet50_vd_imagenet"
    MODEL_SAVE_DIR: "saved_model/deeplabv3p_resnet50_vd_bn_cityscapes"
    SNAPSHOT_EPOCH: 10
    SYNC_BATCH_NORM: True
TEST:
    TEST_MODEL: "saved_model/deeplabv3p_resnet50_vd_bn_cityscapes/final"
SOLVER:
    LR: 0.05
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"
    NUM_EPOCHS: 700
