_base_: './cityscapes.yml'

train_dataset:
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [769, 769]
    - type: RandomHorizontalFlip
    - type: Normalize

val_dataset:
  transforms:
    - type: Padding
      target_size: [2045, 1025]
    - type: Normalize
