shortcut:
  change_output_dir: Shift+Z
  clear: Ctrl+Shift+Z
  finish_object: Space
  open_folder: Shift+A
  open_image: Ctrl+A
  redo: Ctrl+Y
  turn_next: F
  turn_prev: S
  undo: Ctrl+Z
  load_param: Ctrl+M
